export const mySkills = [
  {
    alt: "Sitio web de Bash",
    img: "skills/bash.png",
    name: "Bash",
    href: "https://www.gnu.org/software/bash/",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de CSS",
    img: "skills/css.png",
    name: "CSS",
    href: "https://www.w3.org/Style/CSS/Overview.en.html",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de Debian",
    img: "skills/debian.png",
    name: "Debian",
    href: "https://www.debian.org/",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de Github",
    img: "skills/github1.png",
    name: "Gihub",
    href: "https://www.github.com",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de Gitlab",
    img: "skills/gitlab1.png",
    name: "Gitlab",
    href: "https://www.github.com",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de HTML",
    img: "skills/html.png",
    name: "HTML",
    href: "https://html.com/",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de Javascript",
    img: "skills/javascript.png",
    name: "Javascript",
    href: "https://www.javascript.com/",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de KVM",
    img: "skills/kvm3.png",
    name: "KVM",
    href: "https://www.linux-kvm.org/page/Main_Page",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de NextJS",
    img: "skills/nextjs.png",
    name: "NextJS",
    href: "https://nextjs.org/",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de NodeJS",
    img: "skills/nodejs.png",
    name: "NodeJS",
    href: "https://nodejs.org/en/",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de Python",
    img: "skills/python.png",
    name: "Python",
    href: "https://www.python.org/",
    target: "_blank",
    rel: "noreferrer",
  },
  {
    alt: "Sitio web de Red Hat",
    img: "skills/red-hat.png",
    name: "Red Hat",
    href: "https://www.redhat.com/en",
    target: "_blank",
    rel: "noreferrer",
  },
];

export const myProjects = [
  {
    title: "Este sitio - contenido web estático",
    // skills/bash.png
    backgroundImg: "projects/srv-lamp.jpg",
    projectUrl: "static-portfolio-01",
    tech: "React - Next",
    alt: "Portfolio estático",
  },
  {
    title: "Srv Kubernetes Minikube",
    backgroundImg: "projects/srv-minikube.jpg",
    projectUrl: "server-k8s",
    tech: "Contenedores - k8s",
    alt: "Servidor k8s",
  },
  {
    title: "KVM - multiples guest RHEL 9",
    backgroundImg: "projects/kvm-guest-rhel9.jpg",
    projectUrl: "kvm-guest",
    tech: "KVM - RHEL 9",
    alt: "KVM multiples VMS rhel 9"
  },
  {
    title: "Sevidor MicroK8s",
    backgroundImg: "projects/microk8s.jpg",
    projectUrl: "microk8s",
    tech: "Contenedores - MicroK8s",
    alt: "Servidor Microk8s",
  },
];
