import Head from "next/head";
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import Skills from "../components/Skills";
import Projects from "../components/Projects";

/*
import About from "../components/About";
import Contact from "../components/Contact";
*/

export default function Home() {
  return (
    <div>
      <Head>
        <title>Daniel Zamo | Linux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <Projects />
      <Skills />
      {/** <About />
            <Contact />
      
      */}
    </div>
  );
}
